# Add your GitHub Sponsors username (if you have one)
github: [Godsend69]

# Add other sponsorship platforms below if you use them (remove lines you don't use)
# Example: ko_fi: Godsend69
# Example: patreon: Godsend69

# For custom links (like PayPal, Buy Me a Coffee, etc.)
custom:
  - label: "Buy Me a Coffee"
    url: "https://www.buymeacoffee.com/Godsend69"
  - label: "PayPal"
    url: "https://www.paypal.me/Godsend69"
